version: "3.8"

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    volumes:
      - ..:/workspace
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:?}:${POSTGRES_PASSWORD:?}@db:5432/${POSTGRES_DB:?}
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    depends_on:
      - db
    platform: linux/x86_64
    networks:
      ktg-net:

  selenium_chrome:
    image: seleniarm/standalone-chromium
    networks:
      ktg-net:


  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    ports:
      - "5432:5432"
    healthcheck:
      test: 'pg_isready -U ${POSTGRES_USER:?} || exit 1'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      ktg-net:

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

networks:
  ktg-net:
